# Generated by Django 2.2.10 on 2020-03-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='forma_envio',
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_envio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.FormaEnvio'),
            preserve_default=False,
        ),
    ]
