# Generated by Django 2.2.10 on 2020-03-23 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0003_pessoa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=0, max_length=255, upload_to='imagens/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_da_venda',
            field=models.DateField(verbose_name='data da venda'),
        ),
    ]
