# Generated by Django 2.2.10 on 2020-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20200323_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
