# Generated by Django 2.2.10 on 2020-03-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20200325_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtovenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Produto'),
        ),
    ]
