# Generated by Django 2.2.10 on 2020-04-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20200402_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtovenda',
            old_name='quantidade',
            new_name='qtde',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='valor_envio',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='produtovenda',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_da_venda',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.CharField(blank=True, choices=[('00%', 'Venda sem desconto'), ('05%', '05%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('75%', '75%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.FormaEnvio'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.FormaPagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
