# Generated by Django 2.2.10 on 2020-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20200402_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_da_venda',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
