# Generated by Django 2.2.10 on 2020-04-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20200406_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtovenda',
            old_name='quantidade',
            new_name='qtde',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='valor_envio',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='produtovenda',
            name='preco',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
            preserve_default=False,
        ),
    ]
