# Generated by Django 2.2.10 on 2020-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20200407_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
