# Generated by Django 2.2.10 on 2020-04-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='desconto',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
