# Generated by Django 2.2.10 on 2020-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_auto_20200412_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
