# Generated by Django 2.2.10 on 2020-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_auto_20200414_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='validade',
            field=models.DateField(null=True, verbose_name='data de validade'),
        ),
    ]
