# Generated by Django 2.2.10 on 2020-04-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20200414_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Produto')),
            ],
        ),
    ]
