# Generated by Django 2.2.10 on 2020-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_entradaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproduto',
            name='data_entrada',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
