# Generated by Django 2.2.10 on 2020-04-16 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_entradaproduto_data_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.DecimalField(decimal_places=2, max_digits=50)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=50)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Venda')),
            ],
        ),
    ]
