# Generated by Django 2.2.10 on 2020-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='parcelas',
            field=models.IntegerField(choices=[('1', 'À Vista'), ('2', '2x'), ('3', '3x')]),
        ),
    ]
