# Generated by Django 2.2.10 on 2020-04-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_auto_20200417_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='parcelas',
            field=models.CharField(choices=[('1x', 'À Vista'), ('2', '2x'), ('3', '3x')], max_length=100),
        ),
    ]
