# Generated by Django 2.2.10 on 2020-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_auto_20200422_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='numero_parcela',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='parcelas',
            field=models.CharField(choices=[('1', 'À Vista'), ('2', '2x'), ('3', '3x')], max_length=100),
        ),
    ]
