# Generated by Django 2.2.10 on 2020-04-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_auto_20200423_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-id']},
        ),
    ]
