# Generated by Django 2.2.10 on 2020-04-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_auto_20200423_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaenvio',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cupom de desconto'),
        ),
    ]
